### ISSUE TITLE
Pipelines creation date

### ISSUE THREAD

**Issue by xlecours** [CONP-PCNO/conp-dataset#129] opened 2019-12-17 21:47 UTC
To feed the conp-portal dashboard, we would need the creation date of the pipelines.
Looking at the zenodo_crawler I noticed that a `GET https://zenodo.org/api/records/?type=dataset&q=keywords:%22canadian-open-neuroscience-platform%22` returns an object in which the hits contains a "created" property. Could it be add to the descriptor file?

**Comment by glatard** [comment] 2019-12-18 01:56
@joeyzhou98, could you have a look at that? We need to get the upload date of pipelines, not datasets. I think it might take an update on bosh search.

**Comment by glatard** [comment] 2020-05-13 14:55
Duplicate of https://github.com/CONP-PCNO/conp-portal/issues/248

**Closed by glatard** 2020-05-13 14:55 UTC
Labels: enhancement
