### ISSUE TITLE
Flag datasets as CONP/Canadian/external

### ISSUE THREAD

**Issue by emmetaobrien** [CONP-PCNO/conp-dataset#139] opened 2020-01-15 20:38 UTC
## Purpose

To label each dataset in CONP repository as belonging to one of three categories: a) CONP data; b) other Canadian data; c) data originating external to Canada, in order to better spotlight the focus of the CONP project for users.

## Possible Implementation (optional)

It is proposed to implement this with an additional field in the DATS.json files, under "extraProperties".  I propose calling this "CONP_status" but am open to better suggestions.  Updates will be made implementing this in all CONP datasets within the next couple of days pending receipt of an appropriate "whitelist"/table.

**Comment by glatard** [comment] 2020-01-15 20:41
Makes sense! Maybe we should define what "CONP data" means, as I'm not sure if any data is supposed to be acquired by CONP. 
Also, I think this is a duplicate of https://github.com/CONP-PCNO/conp-portal/issues/153

**Comment by emmetaobrien** [comment] 2020-01-16 15:18
@glatard: My understanding is that this is something Alan has requested to allow us to highlight Canadian data within the portal, and the definition of what counts as CONP data will be supplied to us.

**Closed** 2020-04-27 13:44 UTC
Labels: enhancement
